### ISSUE TITLE
StaffChat color gets reset on new line

### ISSUE THREAD

**Issue by ZachyFoxx** [DumbDogDiner/StickyChat#4]
The staff chat color gets reset on a new line.

To replicate this, enable staff chat and type a message that is longer than the default chat window size.

![image](https://user-images.githubusercontent.com/45671827/98577057-fd8d8280-2280-11eb-8f56-ef5b888df2a8.png)

**Comment by kaylendog** [comment]
Likely borked due to new formatter. Please reopen if this is still an issue.
