### ISSUE TITLE
Escapes available for color codes

### ISSUE THREAD

**Issue by aakatz3** [DumbDogDiner/StickyChat#7]
| Name            | About                            | Title | Labels  | Assignees   |
|-----------------|----------------------------------|-------|---------|-------------|
| Feature request | Hex color code escape characters |       | feature | @SkyezerFox |

**Is your feature request related to a problem? Please describe.**
Hex color codes e.g. (`&#123abc`) cannot be escaped in chat.

**Describe the solution you'd like**
Use `&&` to escape hex color codes.

**Comment by kaylendog** [comment]
I know it's not in the repository, but please use the same issue template as StickyAPI.

**Comment by kaylendog** [comment]
Potential fix made available by expanding the formatting regex to match `&&` as well as `&`, and checking during formatting if the second character exists, thus escaping the rest of the formatting logic.
